#pragma once

// recipeToSource: emit a random machine as a complete, standalone C++ translation
// unit that builds the production Hsm table with explicit builder calls and drives
// it through the exhaustive backbone. The source counterpart to recipeToTable
// (random_codegen.hpp): where that materializes a recipe into a compile-time table
// inside one TU, this emits the recipe as *text* so each random machine compiles
// and runs as its own translation unit -- the path past a single TU's compile
// budget, for fuzzing an unbounded seed range as separate compilations
// (tools/codegen_fuzz.sh).
//
// The emitted TU is self-contained: a literal `.initial/.state/.on/.local/.unwired`
// chain plus a main() that runs runBackbone and exits nonzero on any
// production-vs-reference divergence or a vacuous run -- a standalone reproducer
// for the machine named by (seed, N).

#include <cstddef>
#include <cstdint>
#include <sstream>
#include <string>

#include "eta_hsm/probe/scaling_generator.hpp"
#include "eta_hsm/reference/random_machine.hpp"
#include "eta_hsm/reflect/enum_reflection.hpp"

namespace eta_hsm::reference {

// "ProbeState::<name>" for the enumerator at index k (e.g. ProbeState::S3).
inline std::string stateRef(std::size_t k)
{
    constexpr auto states = eta_hsm::enum_values<ProbeState>();
    auto const n = eta_hsm::enum_name(states[k]);
    return "ProbeState::" + std::string{n ? *n : "S0"};
}

// "ProbeEvent::<name>" for the enumerator at index k (e.g. ProbeEvent::E2).
inline std::string eventRef(std::size_t k)
{
    constexpr auto events = eta_hsm::enum_values<ProbeEvent>();
    auto const n = eta_hsm::enum_name(events[k]);
    return "ProbeEvent::" + std::string{n ? *n : "E0"};
}

// Emit the machine named by (seed, n) as a standalone C++ translation unit. The
// builder chain mirrors recipeToTable's call order exactly -- Top and its Initial
// Substate, then the non-Top States, their composite Initial Substates, the
// Transitions, and finally the unwired enumerators -- so the spelled-out table is
// the same production table recipeToTable yields for the same recipe.
inline std::string recipeToSource(std::uint64_t seed, std::size_t n)
{
    RandomRecipe const r = makeRecipe(seed, n);
    constexpr std::size_t cap = eta_hsm::enum_values<ProbeState>().size();

    std::ostringstream o;
    o << "// Generated by eta_hsm::reference::recipeToSource -- do not edit.\n"
      << "// Random machine seed=" << seed << " states=" << r.states.size() << ".\n"
      << "//\n"
      << "// A standalone reproducer: builds the production Hsm table with explicit\n"
      << "// builder calls and drives it through the exhaustive backbone, exiting\n"
      << "// nonzero on any production-vs-reference divergence or a vacuous run.\n"
      << "\n"
      << "#include <cstddef>\n"
      << "#include <iostream>\n"
      << "\n"
      << "#include \"eta_hsm/machine/hsm.hpp\"\n"
      << "#include \"eta_hsm/machine/machine.hpp\"\n"
      << "#include \"eta_hsm/probe/scaling_generator.hpp\"\n"
      << "#include \"eta_hsm/reference/backbone.hpp\"\n"
      << "#ifdef FUZZ_SELFCHECK\n"
      << "#include \"eta_hsm/reference/random_machine.hpp\"\n"
      << "#endif\n"
      << "\n"
      << "namespace {\n"
      << "using eta_hsm::Hsm;\n"
      << "using eta_hsm::probe::ProbeEvent;\n"
      << "using eta_hsm::probe::ProbeHost;\n"
      << "using eta_hsm::probe::ProbeState;\n"
      << "\n"
      << "// The random machine's production table, spelled out call by call.\n"
      << "consteval auto makeFuzzTable()\n"
      << "{\n"
      << "    Hsm<ProbeHost, ProbeState, ProbeEvent> m{};\n";

    // Top (the isTop root) and its Initial Substate.
    o << "    m = m.initial(" << stateRef(r.states[0].index) << ", " << stateRef(r.states[0].initial) << ");\n";

    // Attach every non-Top State under its parent.
    for (std::size_t i = 1; i < r.states.size(); ++i)
    {
        o << "    m = m.state(" << stateRef(r.states[i].index) << ", " << stateRef(r.states[i].parent) << ");\n";
    }

    // Give every non-Top Composite State its Initial Substate.
    for (std::size_t i = 1; i < r.states.size(); ++i)
    {
        if (r.states[i].hasInitial)
        {
            o << "    m = m.initial(" << stateRef(r.states[i].index) << ", " << stateRef(r.states[i].initial) << ");\n";
        }
    }

    // Each Transition: .local for the Local dispatch variant, .on for External.
    for (auto const& t : r.transitions)
    {
        char const* const verb = t.local ? "local" : "on";
        o << "    m = m." << verb << "(" << stateRef(t.source) << ", " << eventRef(t.event) << ", "
          << stateRef(t.target) << ");\n";
    }

    // Opt the enumerators the recipe never wired out of the exhaustiveness check.
    for (std::size_t i = r.states.size(); i < cap; ++i)
    {
        o << "    m = m.unwired(" << stateRef(i) << ");\n";
    }

    o << "    return m;\n"
      << "}\n"
      << "constexpr auto kFuzzTable = makeFuzzTable();\n"
      << "}  // namespace\n"
      << "\n"
      << "int main()\n"
      << "{\n"
      << "#ifdef FUZZ_SELFCHECK\n"
      << "    // Faithfulness: re-derive this machine independently from the seed and\n"
      << "    // assert the spelled-out table matches it, so an emitter bug that wires a\n"
      << "    // valid-but-wrong machine is caught here rather than silently fuzzed.\n"
      << "    {\n"
      << "        auto const emitted = eta_hsm::reference::makeTableView<kFuzzTable>();\n"
      << "        auto const oracle = eta_hsm::reference::recipeToView(eta_hsm::reference::makeRecipe(" << seed
      << "ull, " << n << "ull));\n"
      << "        if (!eta_hsm::reference::sameMachine(emitted, oracle))\n"
      << "        {\n"
      << "            std::cerr << \"FAIL: emitted table does not match the recipe for seed " << seed << "\\n\";\n"
      << "            return 1;\n"
      << "        }\n"
      << "    }\n"
      << "#endif\n"
      << "    auto const report = eta_hsm::reference::runBackbone<kFuzzTable>();\n"
      << "    for (auto const& f : report.failures)\n"
      << "    {\n"
      << "        std::cerr << \"FAIL: \" << f << \"\\n\";\n"
      << "    }\n"
      << "    if (!report.ok())\n"
      << "    {\n"
      << "        return 1;\n"
      << "    }\n"
      << "    if (report.pairsVerified == 0)\n"
      << "    {\n"
      << "        std::cerr << \"FAIL: vacuous -- no reachable (Leaf, Event) pair verified\\n\";\n"
      << "        return 1;\n"
      << "    }\n"
      << "    std::cout << \"OK seed=" << seed << " states=" << r.states.size() << " pairs=\" << report.pairsVerified\n"
      << "              << \"\\n\";\n"
      << "    return 0;\n"
      << "}\n";

    return o.str();
}

}  // namespace eta_hsm::reference
