load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "reflection_smoke_test",
    srcs = ["reflection_smoke_test.cpp"],
    deps = [
        "//eta_hsm:eta_hsm",
        "@googletest//:gtest_main",
    ],
)
