load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "reflection_smoke_test",
    srcs = ["reflection_smoke_test.cpp"],
    deps = [
        "//eta_hsm:eta_hsm",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "enum_reflection_test",
    srcs = ["enum_reflection_test.cpp"],
    deps = [
        "//eta_hsm:eta_hsm",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "cd_player_test",
    srcs = ["cd_player_test.cpp"],
    deps = [
        "//eta_hsm:eta_hsm",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "nested_test",
    srcs = ["nested_test.cpp"],
    deps = [
        "//eta_hsm:eta_hsm",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "during_test",
    srcs = ["during_test.cpp"],
    deps = [
        "//eta_hsm:eta_hsm",
        "@googletest//:gtest_main",
    ],
)
