#!/usr/bin/env bash
# Compile-time scaling probe harness.
#
# De-risks the PRD's flagged primary risk: the v2 core leans on P2996 reflection
# and P1306 expansion statements, which are compile-time-heavy, and the spike is
# 7 States while a large machine is 45. This sweeps a synthetic N-State machine
# (eta_hsm/probe/scaling_probe_main.cpp, built by generate<N, Depth>()) across a
# range spanning 7 -> 45 and a little beyond, at two hierarchy depths and two
# optimization levels, compiling each under GCC 16 with -ftime-report and
# recording wall-clock compile time and peak GC memory (GGC).
#
# Output (under docs/, which is gitignored -- the report is on-disk per the
# project convention, not committed):
#   docs/probes/0012-scaling.csv             raw per-point measurements
#   docs/probes/0012-compile-time-scaling.md the report: curve + go/no-go read
#
# Repeatable: re-running regenerates both from scratch. Run it in the toolchain
# container from the repo root:
#
#   ./docker_build bash tools/scaling_probe.sh
#
# The compiler defaults to g++-16 but honors $CXX. Override the sweep with the
# PROBE_NS / PROBE_DEPTHS / PROBE_OPTS env vars (space-separated).

set -euo pipefail

readonly CXX="${CXX:-g++-16}"
readonly SRC="eta_hsm/probe/scaling_probe_main.cpp"
readonly OUT_DIR="docs/probes"
readonly CSV="${OUT_DIR}/0012-scaling.csv"
readonly REPORT="${OUT_DIR}/0012-compile-time-scaling.md"

# Sweep: 7 (the spike) -> 45 (large) and a little beyond, at a flat (Depth 1)
# and a nested (Depth 3) shape, under -O0 (frontend + codegen, isolating the
# reflection/expansion risk) and -O2 (a realistic release build's wall time).
read -r -a NS <<<"${PROBE_NS:-7 12 16 20 25 30 35 40 45 50 56 60}"
read -r -a DEPTHS <<<"${PROBE_DEPTHS:-1 3}"
read -r -a OPTS <<<"${PROBE_OPTS:-O0 O2}"

mkdir -p "${OUT_DIR}"

echo "opt,depth,n,wall_s,ggc_mb" >"${CSV}"

# Compile one (opt, depth, n) point and append a CSV row. Parses the -ftime-report
# TOTAL line, whose last two fields are wall seconds and GGC peak (e.g. "164M").
measure() {
    local opt="$1" depth="$2" n="$3"
    local report
    report="$("${CXX}" -std=c++26 -freflection -I . "-${opt}" -c -ftime-report \
        "-DPROBE_N=${n}" "-DPROBE_DEPTH=${depth}" "${SRC}" -o /tmp/probe_scaling.o 2>&1)"
    local total
    total="$(grep -E '^ TOTAL' <<<"${report}" | tail -1)"
    awk -v opt="${opt}" -v depth="${depth}" -v n="${n}" '
        {
            wall = $(NF - 1)
            mem  = $NF
            unit = mem; sub(/[0-9.]+/, "", unit)
            val  = mem;  sub(/[a-zA-Z]+$/, "", val)
            if (unit == "G")      mb = val * 1024
            else if (unit == "M") mb = val
            else if (unit == "k") mb = val / 1024
            else                  mb = val / (1024 * 1024)
            printf "%s,%s,%s,%.2f,%.1f\n", opt, depth, n, wall, mb
        }' <<<"${total}" >>"${CSV}"
}

echo "Sweeping N=[${NS[*]}] depth=[${DEPTHS[*]}] opt=[${OPTS[*]}] with ${CXX}..."
for opt in "${OPTS[@]}"; do
    for depth in "${DEPTHS[@]}"; do
        for n in "${NS[@]}"; do
            measure "${opt}" "${depth}" "${n}"
            echo "  ${opt} depth=${depth} N=${n} -> $(tail -1 "${CSV}")"
        done
    done
done

# ---------------------------------------------------------------------------
# Render the report: per-configuration tables plus a data-driven go/no-go read.
# The verdict compares the spike (N=7) to large machines (N=45) under -O2 at the deeper
# shape -- the closest stand-in for a realistic large build -- reporting the growth
# multipliers and the empirical log-log exponent, then judging against fixed
# acceptability gates (a large machine compiles in under 10 s and 2 GB, and grows no
# worse than ~quadratically).
# ---------------------------------------------------------------------------
{
    echo "# 0012 — Compile-time scaling probe report"
    echo
    echo "_Generated by \`tools/scaling_probe.sh\`. Re-run to refresh._"
    echo
    echo "Synthetic N-State machines from \`generate<N, Depth>()\` compiled under"
    echo "GCC 16 / \`-std=c++26 -freflection\`, timed with \`-ftime-report\`. Wall is"
    echo "the TOTAL compile time; memory is peak GC allocation (GGC)."
    echo
    echo "## What this measures (and what it does not)"
    echo
    echo "The probe varies the number of wired States (N) and the tree depth, holding"
    echo "the rest of the toolchain fixed. Two costs scale with N and are what the"
    echo "curve captures: the **P1306 dispatch expansion** (one comparison generated"
    echo "per Transition, ~3N of them) and the **validator's checks** (O(Transitions^2)"
    echo "for the duplicate-pair scan). What is *constant* across the sweep is the"
    echo "**P2996 reflection over the State enum's enumerators** (\`run_hook\` expands"
    echo "over a fixed 64-enumerator \`ProbeState\`, independent of N) — so it sits in"
    echo "the intercept, not the slope. The read is therefore conservative on the"
    echo "reflection axis: a real large machine declares exactly its own States, so"
    echo "its reflection cost is *no larger* than this fixed baseline. The slope below"
    echo "is the genuine per-State growth."
    echo
    for opt in "${OPTS[@]}"; do
        for depth in "${DEPTHS[@]}"; do
            shape="nested (~${depth} deep)"
            [ "${depth}" = "1" ] && shape="flat (star under Top)"
            echo "## -${opt}, ${shape}"
            echo
            echo "| States (N) | Compile (s) | Peak GGC (MB) |"
            echo "| ---------: | ----------: | ------------: |"
            awk -F, -v opt="${opt}" -v depth="${depth}" \
                'NR>1 && $1==opt && $2==depth {printf "| %d | %.2f | %.0f |\n", $3, $4, $5}' "${CSV}"
            echo
        done
    done

    echo "## Go / no-go read"
    echo
    awk -F, '
        NR>1 {
            key = $1 "," $2
            wall[$1","$2","$3] = $4
            mem[$1","$2","$3]  = $5
        }
        END {
            opt = "O2"; depth = (3 in seen) ? 3 : 3
            # Prefer the deeper -O2 shape; fall back if absent.
            d = 3
            if (!(("O2," d ",45") in wall)) d = 1
            t7  = wall["O2," d ",7"];  t45 = wall["O2," d ",45"]
            m7  = mem["O2," d ",7"];   m45 = mem["O2," d ",45"]
            t60 = wall["O2," d ",60"]; m60 = mem["O2," d ",60"]
            tr  = (t7 > 0) ? t45 / t7 : 0
            mr  = (m7 > 0) ? m45 / m7 : 0
            expn = (t7 > 0 && t45 > 0) ? log(t45/t7) / log(45.0/7.0) : 0
            printf "Reference shape: **-O2, depth %d** (closest to a realistic large build).\n\n", d
            printf "- Spike (N=7): **%.2f s**, **%.0f MB**.\n", t7, m7
            printf "- Large (N=45): **%.2f s**, **%.0f MB** — %.1fx time, %.1fx memory vs the spike.\n", t45, m45, tr, mr
            if (t60 != "") printf "- Beyond (N=60): **%.2f s**, **%.0f MB**.\n", t60, m60
            printf "- Empirical growth exponent (log-log, 7→45): **%.2f** (1.0 = linear, 2.0 = quadratic).\n\n", expn
            pass = (t45 < 10.0 && m45 < 2048.0 && expn < 2.2)
            if (pass)
                printf "**GO.** A large (45-State) machine compiles in %.2f s using %.0f MB, growing ~N^%.1f — sub-quadratic and well within budget. The reflection + expansion design scales to large machines.\n", t45, m45, expn
            else
                printf "**NO-GO / CAUTION.** Large compiles in %.2f s using %.0f MB (exponent ~%.1f). This approaches or exceeds the acceptability gates (10 s / 2 GB / N^2.2); the curve shows a wall worth a HITL decision before committing.\n", t45, m45, expn
        }' "${CSV}"
    echo
    echo "_Acceptability gates: a large machine (N=45) under 10 s wall and 2 GB peak, growth no worse than ~N^2.2._"
} >"${REPORT}"

echo
echo "Wrote ${CSV} and ${REPORT}."
